# Generated by Django 3.1.5 on 2021-01-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemsmodel',
            name='product',
        ),
    ]
