# Generated by Django 3.1.5 on 2021-01-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitemsmodel_product'),
        ('order', '0013_auto_20210114_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_items',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_items',
            field=models.ManyToManyField(related_name='cart_items', to='cart.CartItemsModel'),
        ),
    ]
